name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build the Docker image from our robust Dockerfile
      - name: Build Docker image
        run: docker build -t automation-framework .

      # Run the tests inside the container and create a 'target' folder on the runner
      - name: Run tests in Docker
        run: docker run --name test-run -v ${{ github.workspace }}/target:/app/target automation-framework

      # Upload the HTML report from the runner's 'target' folder
      - name: Upload HTML test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: target/extent-report.html

      # Upload the XML reports
      - name: Upload XML test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/